version: '2.2'
services:
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.2
    container_name: es01
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es02,es03
      - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - data01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - elastic

  es02:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.2
    container_name: es02
    environment:
      - node.name=es02
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es01,es03
      - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - data02:/usr/share/elasticsearch/data
    networks:
      - elastic

  es03:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.2
    container_name: es03
    environment:
      - node.name=es03
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es01,es02
      - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - data03:/usr/share/elasticsearch/data
    networks:
      - elastic

  kib01:
    image: docker.elastic.co/kibana/kibana:7.15.2
    container_name: kib01
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_URL: http://es01:9200
      ELASTICSEARCH_HOSTS: '["http://es01:9200","http://es02:9200","http://es03:9200"]'
    networks:
      - elastic

volumes:
  data01:
    driver: local
  data02:
    driver: local
  data03:
    driver: local

networks:
  elastic:
    driver: bridge



# version: "3.7"

# services:
#   # Elasticsearch Docker Images: https://www.docker.elastic.co/
#   elasticsearch01:
#     image: docker.elastic.co/elasticsearch/elasticsearch:7.4.0
#     container_name: elasticsearch01
#     environment:
#       - cluster.name=es-docker-cluster
#       - node.name=esNode01
#       - discovery.seed_hosts=esNode02, esNode03
#       - cluster.initial_master_nodes=esNode01,esNode02,esNode03
#       - bootstrap.memory_lock=true
#       - xpack.security.enabled=false
#       # - discovery.type=single-node
#       - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
#     ulimits:
#       memlock:
#         soft: -1
#         hard: -1
#       # nofile:
#       #   soft: 65536
#       #   hard: 65536
#     # cap_add:
#     #   - IPC_LOCK
#     volumes:
#       - elasticsearch-data-node1:/usr/share/elasticsearch/data
#     ports:
#       - 9200:9200
#       - 9300:9300
#     networks:
#       - es_network
    
      
#   elasticsearch02:
#     image: docker.elastic.co/elasticsearch/elasticsearch:7.4.0
#     container_name: elasticsearch02
#     environment:
#       - cluster.name=es-docker-cluster
#       - node.name=esNode02
#       - discovery.seed_hosts=esNode01,esNode03
#       - cluster.initial_master_nodes=esNode01,esNode02,esNode03
#       - bootstrap.memory_lock=true
#       - xpack.security.enabled=false
#       # - discovery.type=single-node
#       - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
#     ulimits:
#       memlock:
#         soft: -1
#         hard: -1
#       # nofile:
#       #   soft: 65536
#       #   hard: 65536
#     # cap_add:
#     #   - IPC_LOCK
#     volumes:
#       - elasticsearch-data-node2:/usr/share/elasticsearch/data
#     # ports:
#     #   - 9200:9202
#     #   # - 9300:9300
#     networks:
#       - es_network


#   elasticsearch03:
#     image: docker.elastic.co/elasticsearch/elasticsearch:7.4.0
#     container_name: elasticsearch03
#     environment:
#       - bootstrap.memory_lock=true
#       - cluster.name=es-docker-cluster
#       - node.name=esNode03
#       - discovery.seed_hosts=esNode01,esNode02
#       - cluster.initial_master_nodes=esNode01,esNode02,esNode03
#       - xpack.security.enabled=false
#       - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
#       # - discovery.type=single-node
#     ulimits:
#       memlock:
#         soft: -1
#         hard: -1
#       # nofile:
#       #   soft: 65536
#       #   hard: 65536
#     # cap_add:
#     #   - IPC_LOCK
#     volumes:
#       - elasticsearch-data-node3:/usr/share/elasticsearch/data
#     # ports:
#     #   - 9200:9203
#       # - 9300:9300
#     networks:
#       - es_network

#   kibana:
#     container_name: kibana
#     image: docker.elastic.co/kibana/kibana:7.4.0
#     environment:
#       ELASTICSEARCH_HOSTS: '["http://elasticsearch01:9200","http://elasticsearch02:9200","http://elasticsearch03:9200"]'
#     ports:
#       - 5601:5601
#     networks:
#       - es_network
#     # depends_on:
#     #   - elasticsearch01
#     #   - elasticsearch02
#     #   - elasticsearch03

# volumes:
#   elasticsearch-data-node1:
#     driver: local
#   elasticsearch-data-node2:
#     driver: local
#   elasticsearch-data-node3:
#     driver: local

# networks:
#   es_network:
#     driver: bridge
